### PR TITLE
Upgrade to JupyterLab 4.0

### LINKED ISSUE #64: Compatibility with jupyter-server 2.x/Jupyterlab 4.x
I tried to use jupyterlab-citation-manager but failed to succeed.

Installed the extension in the jupyterlab extension manager, added an API key refreshed the page/restarted the server but no entries can be found.

When I try to install it using poetry I get the following message
```
Using version ^0.3.2 for jupyterlab-citation-manager

Updating dependencies
Resolving dependencies... (0.1s)

Because no versions of jupyterlab-myst match >2,<2.0.1 || >2.0.1,<3
 and jupyterlab-myst (2.0.0) depends on jupyter-server (>=2.0.1,<3), jupyterlab-myst (>=2,<2.0.1 || >2.0.1,<3) requires jupyter-server (>=2.0.1,<3).
And because jupyterlab-myst (2.0.1) depends on jupyter-server (>=2.0.1,<3), jupyterlab-myst (>=2,<3) requires jupyter-server (>=2.0.1,<3).
Because no versions of jupyterlab-citation-manager match >0.3.2,<0.4.0
 and jupyterlab-citation-manager (0.3.2) depends on jupyter-server (>=1.6,<2), jupyterlab-citation-manager (>=0.3.2,<0.4.0) requires jupyter-server (>=1.6,<2).
Thus, jupyterlab-citation-manager (>=0.3.2,<0.4.0) is incompatible with jupyterlab-myst (>=2,<3).
So, because ads-b simulator depends on both jupyterlab-myst (^2) and jupyterlab-citation-manager (^0.3.2), version solving failed.
```

Does jupyterlab-citation-manager not work with the jupyter-server v2 but the Jupyterlab Extension Manager just ignores the requirements?

Or is the problem that I'm using jupyterlab version 4.0.5 which seems to collide with e.g. 

https://github.com/krassowski/jupyterlab-citation-manager/blob/351f616fe6b8532674729d55bee7f584802d660e/pyproject.toml#L2

https://github.com/krassowski/jupyterlab-citation-manager/blob/351f616fe6b8532674729d55bee7f584802d660e/package.json#L60-L62

?

### PR DESCRIPTION
**Pull request by krassowski**
Closes #64
- [x] ran the extension migration script as suggested by the [migration documentation](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#upgrading-extension-using-the-upgrade-script)
- [x] removed `node_modules` and recreated lock file
- [x] updated the APIs for metadata and source manipulation

### CODE REVIEW

**Comment by krassowski** [comment]
```
      Building extension in .
      /tmp/pip-build-env-7c7udazz/overlay/lib/python3.11/site-packages/jupyterlab/debuglog.py:56: UserWarning: An error occurred.
        warnings.warn("An error occurred.")
      /tmp/pip-build-env-7c7udazz/overlay/lib/python3.11/site-packages/jupyterlab/debuglog.py:57: UserWarning: ValueError: Could not find @jupyterlab/builder
        warnings.warn(msg[-1].strip())
      /tmp/pip-build-env-7c7udazz/overlay/lib/python3.11/site-packages/jupyterlab/debuglog.py:58: UserWarning: See the log file for details: /tmp/jupyterlab-debug-175ublvk.log
```

Huh?

**Comment by jtpio** [comment]
Maybe a missing `.yarnrc.yml` with `nodeLinker: node-modules`?

**Comment by krassowski** [comment]
That was it thank you!

**Comment by krassowski** [comment]
bot please update snapshots

**Comment by krassowski** [comment]
Integration failures seem relevant, will need to test locally.

**Comment by krassowski** [comment]
The relevant part of logs appears to be:
```
[WebServer] [I 2023-12-13 13:49:14.156 ServerApp] Looking for CSL styles for Citation Manager in ['/home/runner/.local/share/jupyter/csl-styles', '/opt/hostedtoolcache/Python/3.11.7/x64/share/jupyter/csl-styles', '/usr/local/share/jupyter/csl-styles', '/usr/share/jupyter/csl-styles']
[WebServer] [I 2023-12-13 13:49:14.156 ServerApp] Located 0 CSL styles for Citation Manager.
[WebServer] [I 2023-12-13 13:49:14.156 ServerApp] Registered jupyterlab_citation_manager extension at URL path /citation-manager
```

For some reason styles are not found.

**Pull request merged**
